FROM postgres:15-alpine3.17

COPY docker/postgres/postgresql.conf.sample /usr/local/share/postgresql/postgresql.conf.sample

COPY docker/postgres/docker-entrypoint-initdb.d /docker-entrypoint-initdb.d